### ISSUE TITLE
Create GitHub action to build and publish ui shared modules

### ISSUE THREAD

**Issue by dbadham-fr** [SecureApiGateway/SecureApiGateway#806] opened 2023-02-08 15:38 UTC
https://github.com/SecureApiGateway/securebanking-ui contains `securebanking-ui-common` and `securebanking-ui-cli` modules, these modules are dependencies of the rcs and swagger UIs.

The way that the rcs ui is built, means that changes to the cli or common module are not picked up in docker images built from a PR, as the packages are pulled from npm registry.

Create GitHub action to build and publish the modules.

Currently these modules have to be built manually, this needs to be automated.

**Comment by shaunharrisonFR** [comment] 2023-06-15 09:20
@jorgesanchezperez what commands to you currently run manually to build the common and ui cli?

**Comment by BohoCode** [comment] 2023-09-27 14:03
duplicate of #930 ?

**Closed by BohoCode** 2023-09-27 14:03 UTC
Labels: duplicate, devops
