### ISSUE TITLE
Create IG Java library to implement DCR

### ISSUE THREAD

**Issue by dbadham-fr** [SecureApiGateway/SecureApiGateway#631] opened 2022-11-01 14:38 UTC
The DCR logic is complex and has no unit tests. The logic is spread across several filters and IG route config.

In order to make DCR easier to maintain it should be moved into a Java lib

Key design considerations:

- Keep FAPI DCR and OB specific DCR logic separate
  - In future we may want to only use the FAPI logic
- Library should be easy for clients to plug into a route

**Comment by BohoCode** [comment] 2022-12-05 10:30
Duplicate of #699

**Closed by BohoCode** 2022-12-05 10:30 UTC
Labels: duplicate
