### ISSUE TITLE
Review FAPI Test warning for fapi1-advanced-final-discovery-end-point-verification

### ISSUE THREAD

**Issue by dbadham-fr** [SecureApiGateway/SecureApiGateway#920] opened 2023-03-29 07:03 UTC
FAPI Test: `fapi1-advanced-final-discovery-end-point-verification`

Warning: `CheckJwksUriIsHostedOnOpenBankingDirectory: JWKS URI is not hosted on the OpenBanking Directory. This is acceptable on a sandbox, but production systems must use an OpenBanking Directory hosted JWKS.`

Values
actual: `sapig.ob-sandbox-v1.forgerock.financial`
expected: `keystore.openbanking.org.uk`

We are hosting the JWKS URI in AM, instead it needs to be hosted by the OpenBanking Directory (or OpenBanking Test Directory)

**Comment by BohoCode** [comment] 2023-09-27 15:08
Duplicate of #968

**Closed by BohoCode** 2023-09-27 15:08 UTC
Labels: duplicate, fapi
